Makefile

Calling `make -j1 GIMP= help` results in:
```
Release:
/bin/bash: -c: line 0: unexpected EOF while looking for matching `"'
/bin/bash: -c: line 1: syntax error: unexpected end of file
make: *** [Makefile:706: help] Error 1
```
This is broken since commit b10f57e39342af34209c349ed514d61f10b56386

Makefile: Fix quoting

---

Makefile

Currently only the stderr is ignored, but it is the stdout that is
spammy when '-q' is accepted.

Fix: [Makefile] when testing '-q' for unix2dos, ignore the stdout and stderr

---

.github/workflows/testing.yml
Makefile

Seems we missed a piece of mercurial code in the conversion.

Change: also allow creating a source-tar via git (instead of Mercurial)

---

.gitignore
Makefile

Over time a few things got left behind that appears to have no
function anymore. So let's remove them, and see if anyone notices.

Various of minor stuff

---

Makefile

As GIMP is optional, we can simply continue with the checked-in
cached result.

Fix: [Makefile] autodetect if GIMP is installed

---

.gitignore
Makefile

It looks for readme.txt, license.txt and changelog.txt by name. So
no matter how we call it in the repository, make sure it matches
with the expectation in the tarball.
Fixes https://github.com/OpenTTD/OpenGFX/issues/22

Fix: [Makefile] make sure that filenames in the tarball are as OpenTTD expects

---

.gitignore
Makefile
findversion.sh

'findversion.sh' is a script from the OpenTTD repository. This means
OpenGFX now acts the same as OpenTTD in terms of version, filename,
etc.

Change: [Makefile] replace custom git-detection with 'findversion.sh'

---

Makefile

This means 'make doc' didn't do anything anymore.

Remove: [Makefile] documentation is now supplied, no longer generated

---

Makefile

.dep files were left behind, as some other files were. Normally
this would be fine, but there are cases where the generated .dep
content is invalid. After that, normal users get stuck, as
'make clean' doesn't bring them back to a known-good-state.
Now 'make clean' removes all generated files correctly, meaning
the repository should be back to a known-good-state afterwards.

Fix: [Makefile] make sure 'make clean' cleans all generated files

---

Makefile

Otherwise it barks out with weird errors about '-m' that nobody
is going to piece together. It now returns a proper error a user
can understand .. I hope :D

Fix: [Makefile] tell the user he needs to install grfcodec if grfid is not found

---

.github/workflows/publish.yml
Makefile

This to make the name more in line with other OpenTTD packages.
They all have a postfix to indicate for which OS(-flavor) they work.
By adding "-all", people know they work on all OSes.

Fix: postfix binary bundles with "-all", as they work on all systems

---

Makefile

Due to ealier changes, this was now broken. Source bundling was
reusing parts of the code to bundle "all" packages, but that was
following slightly different rules. This solution is not perfect,
but at least it is functioning again.

Fix: [Makefile] make sure source bundles can be packed again

---

.github/workflows/publish.yml
.github/workflows/testing.yml

The OSes GitHub Actions run on, don't 'apt update' before becoming
available, and those OSes are not updated on a very regular base.
In result, hoping that a 'apt install' works is failing over time,
till the OS is updated again, and it slowly drifts into despair
again.
All this solved by an 'apt update' of course.

Fix: [GitHub Actions] make sure apt-database is in sync

---

Makefile

It looks for readme.txt, license.txt and changelog.txt by name. So no matter
how we call it in the repository, make sure it matches with the expectation
in the installed directory.
This fix was already applied for the tarball in PR #24, but that missed
the filenames used when installing into the filesystem directly. See
also issue #22.

Fix: [Makefile] make sure installed filenames are as OpenTTD expects

---

.github/workflows/publish.yml

Let's fix the trigger to "Update CDN"

Fix: Update CDN event type has been renamed

---

README.md
findversion.sh
lang/english.lng
sprites/extra/extra-header.pnml

Presume that's all correct anyway. Usual amount of testing done (none)
Partial fix for #61 - just hardcode the "1.2.0" string in the error message. I played around with getting rid of STR_GRF_NAME, but concluded you'd have to rip apart the build system to do so (which is terrifying, and probably needs doing at some point anyway). `{TITLE}` looks similar to a `{}` directive anyway, which most translators know not to touch.
Also updated the URL in the description

Some fixes

---

sprites/base/base-4677-toyland-industries.pnml

Simple fix to solve the two issues mentioned. The offsets of the buildings now more closely match that of the original sprites, so they don't glitch during the animation cycle.

Fix #49, #51: Correct sprite offsets for toy factory

---

scripts/translations.sh

Latvian translation uses cases and that results in a broken OBG file.
While fixing that I noticed some missing `grflangid` -> ISO mapping. Easier to spot after reordering stuff.

Fix: ignore cases in translations

---

Makefile

`which` is an external command which isn't required by POSIX.
Debian and other distributions (like Gentoo!) are looking
to drop it from their base set of packages.
Switch to `command -v` which should always work instead.
Signed-off-by: Sam James <sam@gentoo.org>

Makefile: drop usage of 'which'

---

.github/workflows/commit-checker.yml
.github/workflows/publish.yml
.github/workflows/testing.yml

If you want "set -e" it is better to set the shell explicit to bash, which does do exactly this (and some more).
See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference

Change: [CI] update actions to latest and minor touchups

---

.github/workflows/commit-checker.yml
.github/workflows/testing.yml

The checkout-pull-request task v4 relies on node 16 which has been deprecated. 
This causes a warning in the workflow run, which causes the "check-annotations" task to fail. 
v5 uses node 20, and is also used in the main OpenTTD repository. I am fairly confident this will resolve the workflow issue.

Fix: Update checkout-pull-request task

---

.github/dependabot.yml

I think some workflows use outdated actions, dependabot should confirm it.

Add: [Dependabot] introduce Dependabot to keep our workflows up-to-date

---

Makefile

The `Makefile` uses Python to construct the NewGRF version.
The Python "script" is compatible with both Python2 and Python3.
The `Makefile` defaulted to Python2.  Now it's Python3.

Fix: [Makefile] python2 is long dead

---

Makefile

In particular:
- Specify the batch script interpreter to use; GIMP3 provides multiple.
- Use `gimp-console` instead of `gimp` to avoid a [non-interactive mode issue](https://gitlab.gnome.org/GNOME/gimp/-/issues/12042).
This doesn't solve all compatibility problems with GIMP3 yet; we also need to resolve the [removal](https://github.com/OpenTTD/OpenGFX/issues/94#issuecomment-2643514969) of a `gimp-image-get-active-layer` API function in GIMP3.
The changes* here are intended to be backwards-compatible to GIMP2 and have been tested GIMP2.10.34 on Debian stable (bookworm), and also with GIMP3.0.0 RC2 to build the OpenGFX 7.1 sources.
*NB: the `which` command has been [superseded](https://github.com/OpenTTD/OpenGFX/commit/0fda466271cae745f4d3d2b5fcf9b5f361a92ffd) by `command -v` since v7.1 in …

Makefile: update to GIMP3-compatible command-line

---

Makefile
scripts/gimpscript
scripts/gimpscript-v2

This PR extends #96 to re-add gimp2 compatibility as discussed in the comments there.
This includes:
- the one commit from #96 verbatim, which changes the gimpscript file for v2 compatibility
- a new commit re-adding the original gimpscript for v2, with the makefile selecting the right version
I tested this on Debian unstable with both gimp 2.10.34-1+deb12u2 from stable and gimp 3.0.0-2 from unstable.

 Script-Fu: Support GIMP3 in addition to GIMP2
